### ISSUE TITLE
Your problem set allows for the same question with different answers

### ISSUE THREAD

**Issue by dayoungcheong** [quickeducation/final-project#29]
You can input multiple of the same question with different or same answers. This should not be allowed as when asked the same question in the problem set, you cannot distinguish which question goes to which answer.

**Comment by zachp98** [comment]
This is a design decision that we do not believe is a real failure, we don't believe that people would ask the same question in the same problem set due to redundancy. Even if they did, they might want to ask something twice to make sure someone understands, perhaps after a few questions in between that would teach them the answer.
