### ISSUE TITLE
Able to access leaderboard page without signing in

### ISSUE THREAD

**Issue by clairehjk** [quickeducation/final-project#41]
Though the leaderboard page's table is empty, I'm still able to redirect to the leaderboard page without signing in. I believe this should redirect to login page instead.

To recreate:
1. Go to homepage without signing in (if signed in, please sign out).
2. Navigate directly to URL: https://quickeducation442.firebaseapp.com/leaderboards 
3. You will see empty leaderboards page.

**Comment by zachp98** [comment]
We believe that this is not a real failure because it does not interfere with the core functionality of the app. If the user was redirected to the login page, that could cause confusion as to how exactly the navigation bar works and what goes to where. Having an empty leaderboard shows that it exists, but a logged out user can not access it.
