### ISSUE TITLE
Overflow text on large questions

### ISSUE THREAD

**Issue by matthewkli97** [quickeducation/final-project#42]
Reproduction:
1. Create a new problem set.
2. Enter a long question.
3. Create the set and navigate to set.
4. Resize window till overflow occurs.

See image for reference

<img width="917" alt="Screen Shot 2019-06-11 at 1 10 39 AM" src="https://user-images.githubusercontent.com/26758656/59254931-fc68a980-8be5-11e9-98b0-55f5ea819d42.png">

**Comment by zachp98** [comment]
The set only allows questions of up to 120 characters. When following the steps above **exactly** , I found that the question stopped at 120 and extended to the edge, but not the end of the screen. Since I can't replicate the overflow with the exact steps given above, I don't think that this is an issue that is critical to the core functionality of the app.

See below

![issue42](https://user-images.githubusercontent.com/46464552/59297175-79bf0900-8c3c-11e9-82da-e08c8e95000b.PNG)
