### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by jinc132** [quickeducation/final-project#50]
I pressed sign up and and entered a email that consist of random values. Then, pressed on the submit button. However, although it checked for the strength of the password, it does not verify the email whether it is a valid email.

**Comment by zachp98** [comment]
I was not able to replicate this on my own given the description and since there are no reproduction steps. I entered random characters with no '@' sign into the email field and entered a random password, it gave me an error saying invalid email address. Due to these complications with testing the issue, I will assume it is not a real failure of our app
